---
# Include variables and define needed variables.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

# Setup/install tasks.
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Template exports file.
  template:
    src: exports.j2
    dest: /etc/exports
    owner: root
    group: root
    mode: 0644
  notify: restart nfs

- name: Ensure nfs is running.
  service: name={{ nfs_server_daemon }} state={{ nfs_server_state }} enabled={{ nfs_server_enabled }}
  when: nfs_exports|length and nfs_service_managed

- name: Set threadcount for nfsd in sysconfig file
  lineinfile:
      state: present
      insertafter: "^#RPCNFSDCOUNT=16"
      create: no
      line: 'RPCNFSDCOUNT="{{ nfsd_threads }}"'
      dest: '/etc/sysconfig/nfs'
  when: nfs_exports|length and nfs_service_managed

- name: Set threadcount in runtime system
  shell: /usr/bin/echo {{ nfsd_threads }} > /proc/fs/nfsd/threads 
  when: nfs_exports|length and nfs_service_managed
      
